//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe7.Infrastructure.ExceptionLocalize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cafe7.Infrastructure.ExceptionLocalize.ExceptionResource", typeof(ExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} «{1}» قبلا ثبت شده است و تكراري مي باشد..
        /// </summary>
        public static string Cst_ExistItem {
            get {
                return ResourceManager.GetString("Cst_ExistItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود كاربر «{0}» به سيستم انجام نشد. نام كاربري يا رمز عبور اشتباه مي باشد و يا كاربر مجوز ورود به سيستم را ندارد..
        /// </summary>
        public static string Sql_18456 {
            get {
                return ResourceManager.GetString("Sql_18456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان برقراري ارتباط با پايگاه داده وجود ندارد. سرويس پايگاه داده متوقف شده است..
        /// </summary>
        public static string Sql_2 {
            get {
                return ResourceManager.GetString("Sql_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رويه ذخيره شده يا تابع «{0}» شامل پارامتر «{1}» مي باشد ولي به آن ارسال نشده است..
        /// </summary>
        public static string Sql_201 {
            get {
                return ResourceManager.GetString("Sql_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستوني با نام «{0}» وجود ندارد..
        /// </summary>
        public static string Sql_207 {
            get {
                return ResourceManager.GetString("Sql_207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنصري در پايگاه داده با نام «{0}» يافت نشد..
        /// </summary>
        public static string Sql_208 {
            get {
                return ResourceManager.GetString("Sql_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار «{0}» تكراري مي باشد..
        /// </summary>
        public static string Sql_2627 {
            get {
                return ResourceManager.GetString("Sql_2627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رويه ذخيره شده اي با نام «{0}» وجود ندارد..
        /// </summary>
        public static string Sql_2812 {
            get {
                return ResourceManager.GetString("Sql_2812", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان حذف پايگاه داده «{0}» بدليل استفاده در سيستم وجود ندارد..
        /// </summary>
        public static string Sql_3702 {
            get {
                return ResourceManager.GetString("Sql_3702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان دسترسي به پايگاه داده وجود ندارد..
        /// </summary>
        public static string Sql_4060 {
            get {
                return ResourceManager.GetString("Sql_4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستوني با نام «{0}» يا تابعي با نام «{1}» يافت نشد و يا تداخل نام در پرس و جوي ارسالي وجود دارد..
        /// </summary>
        public static string Sql_4121 {
            get {
                return ResourceManager.GetString("Sql_4121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان درج مقدار NULL براي ستون «{0}» از جدول «{1}» وجود ندارد..
        /// </summary>
        public static string Sql_515 {
            get {
                return ResourceManager.GetString("Sql_515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان برقراري ارتباط با پايگاه داده وجود ندارد. نام يا مسير سرور اشتباه مي باشد..
        /// </summary>
        public static string Sql_53 {
            get {
                return ResourceManager.GetString("Sql_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان حذف اين آيتم به دليل وجود وابستگي در سيستم وجود ندارد..
        /// </summary>
        public static string Sql_547_Delete {
            get {
                return ResourceManager.GetString("Sql_547_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان درج اين آيتم به دليل وجود تداخل در سيستم وجود ندارد. (كليد خارجي: {0}، جدول: {1}، ستون: {2}).
        /// </summary>
        public static string Sql_547_Insert {
            get {
                return ResourceManager.GetString("Sql_547_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان ويرايش اين آيتم به دليل وجود وابستگي در سيستم وجود ندارد..
        /// </summary>
        public static string Sql_547_Update {
            get {
                return ResourceManager.GetString("Sql_547_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان تبديل نوع داده اي «{0}» به «{1}» وجود ندارد..
        /// </summary>
        public static string Sql_8114 {
            get {
                return ResourceManager.GetString("Sql_8114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد پارامترهاي ارسالي به رويه ذخيره شده يا تابع «{0}» بيشتر از تعداد پارامترهاي تعيين شده مي باشد..
        /// </summary>
        public static string Sql_8144 {
            get {
                return ResourceManager.GetString("Sql_8144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان برقراري ارتباط با پايگاه داده وجود ندارد. نام سرور پايگاه داده يافت نشد..
        /// </summary>
        public static string Sql_N1 {
            get {
                return ResourceManager.GetString("Sql_N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسير تعيين شده براي فايل در سيستم يافت نشد..
        /// </summary>
        public static string Win_2 {
            get {
                return ResourceManager.GetString("Win_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسير تعيين شده براي شبكه يافت نشد..
        /// </summary>
        public static string Win_53 {
            get {
                return ResourceManager.GetString("Win_53", resourceCulture);
            }
        }
    }
}
