// <auto-generated />
namespace Cafe7.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class C003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(C003));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171324251_C003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
