// <auto-generated />
namespace Cafe7.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class C006 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(C006));
        
        string IMigrationMetadata.Id
        {
            get { return "201807180721132_C006"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
